FROM node:20-alpine AS build

WORKDIR /src

COPY app.js ./app.js

RUN npm install -g terser \
    && terser ./app.js -c -m -o ./app.js

FROM nginx:1.27-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY . /usr/share/nginx/html
COPY --from=build /src/app.js /usr/share/nginx/html/app.js

EXPOSE 80
